version: '3.8'

networks:
  app_network:
    driver: bridge

volumes:
  database_volume:
    driver: local

services:
  app:
    image: 'php:8.3-apache'
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
    networks:
      - app_network

  database:
    image: 'mysql:8'
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - database_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: php_07_advanced
    networks:
      - app_network
